### ISSUE TITLE
Entity Event Nodes are out of date

### ISSUE THREAD

**Issue by Incoherent-Code** [destruc7i0n/bedrock-dot-dev#39]
On [this](https://bedrock.dev/docs/stable/Entity%20Events#Versioned%20Changes) page, you detail 5 nodes: Add Component Group, Remove Component Group, Sequence, Trigger, and Randomize
However, nowadays there are several more.

The official Documentation does not have a list of these, but I know for a fact set_property exists, as shown [here](https://learn.microsoft.com/en-us/minecraft/creator/documents/introductiontoentityproperties) 
In fact, bedrock.dev lacks any mention of Custom Entity Properties at all.

[Bridge. ](https://bridge-core.app/) seems to list a ton of them, but I'd take them with a grain of salt and experiment with them on your own because some of these in the past have been implimented by bridge. (run_command used to be done using minecraft:skin_id and server animation controllers to make commands using component groups, but as far as I can tell it's native now)

![image](https://github.com/destruc7i0n/bedrock-dot-dev/assets/24883579/b857bcac-cbf6-4a45-9b8f-707953742630)

**Comment by SirLich** [comment]
This site (bedrock.dev) is a rehost of Microsofts own documentation, which used to be shipped with Vanilla Packs. Now that they're hosting their own documentation, they've given less and less care to maintaining this docs source, so bedrock.dev becomes less and less up to date. 

The "user curated" section of the site is wiki.bedrock.dev, although admittedly, this is also drifting out of date, due to lowish contributions.

**Comment by Incoherent-Code** [comment]
Ah, my bad. I forgot that wiki.bedrock.dev existed, since its usually not featured very highly in search results and tools like bridge still direct to bedrock.dev
